# Count data-point folders by region

Expected structure:

```text
ROOT_FOLDER/
├── Abruzzo/
│   ├── datapoint_001/
│   ├── datapoint_002/
│   └── ...
├── Basilicata/
│   ├── datapoint_001/
│   └── ...
└── ... 20 region folders
```

The notebook counts only the **immediate child folders inside each region folder** as data points.  
This avoids accidentally counting folders nested inside a data-point folder.

In [3]:
from pathlib import Path
import pandas as pd

# Change this to your real outer folder.
ROOT_FOLDER = Path("./0.original_foto_schede/")

# macOS / Linux example:
# ROOT_FOLDER = Path("/Users/yourname/path/to/outside_folder")

ROOT_FOLDER

PosixPath('0.original_foto_schede')

In [4]:
# Basic validation
if not ROOT_FOLDER.exists():
    raise FileNotFoundError(f"Folder does not exist: {ROOT_FOLDER}")

if not ROOT_FOLDER.is_dir():
    raise NotADirectoryError(f"Path is not a folder: {ROOT_FOLDER}")

region_folders = sorted(
    folder
    for folder in ROOT_FOLDER.iterdir()
    if folder.is_dir()
)

print(f"Region folders found: {len(region_folders)}")

if len(region_folders) != 20:
    print("Warning: expected 20 region folders.")

Region folders found: 20

In [5]:
# Count immediate data-point folders inside each region folder
rows = []

for region_folder in region_folders:
    data_point_folders = sorted(
        folder
        for folder in region_folder.iterdir()
        if folder.is_dir()
    )

    rows.append({
        "region": region_folder.name,
        "data_points": len(data_point_folders),
        "region_path": str(region_folder),
    })

counts_df = pd.DataFrame(rows).sort_values("region").reset_index(drop=True)

display(counts_df)

total_data_points = int(counts_df["data_points"].sum())

print(f"\nTotal data points: {total_data_points:,}")

            region  data_points                            region_path
0          abruzzo           19         0.original_foto_schede/abruzzo
1       basilicata           18      0.original_foto_schede/basilicata
2         calabria           18        0.original_foto_schede/calabria
3         campania           22        0.original_foto_schede/campania
4   emilia_romagna            8  0.original_foto_schede/emilia_romagna
5           friuli            4          0.original_foto_schede/friuli
6            lazio          126           0.original_foto_schede/lazio
7          liguria           37         0.original_foto_schede/liguria
8        lombardia           25       0.original_foto_schede/lombardia
9           marche           33          0.original_foto_schede/marche
10          molise           17          0.original_foto_schede/molise
11        piemonte           33        0.original_foto_schede/piemonte
12          puglia           28          0.original_foto_schede/puglia
13        sardegna           14        0.original_foto_schede/sardegna
14         sicilia           13         0.original_foto_schede/sicilia
15         toscana            8         0.original_foto_schede/toscana
16        trentino            7        0.original_foto_schede/trentino
17          umbria           36          0.original_foto_schede/umbria
18       val_aosta           21       0.original_foto_schede/val_aosta
19          veneto            2          0.original_foto_schede/veneto

Total data points: 489

In [6]:
# Optional: show every detected data-point folder
data_points = []

for region_folder in region_folders:
    for data_point_folder in sorted(region_folder.iterdir()):
        if data_point_folder.is_dir():
            data_points.append({
                "region": region_folder.name,
                "data_point": data_point_folder.name,
                "path": str(data_point_folder),
            })

data_points_df = pd.DataFrame(data_points)

display(data_points_df.head(50))
print(f"Detected data-point folders: {len(data_points_df):,}")

,region,data_point,path
0,abruzzo,1300309704_CH_Ortona_EDSING_scala est_Masseria...,0.original_foto_schede/abruzzo/1300309704_CH_O...
1,abruzzo,1300309779_PE_Mosciano Sant_Angelo_EDNN_scala ...,0.original_foto_schede/abruzzo/1300309779_PE_M...
2,abruzzo,1300310044_AQ_Balsorano_EDSING_casa pendio_Alf...,0.original_foto_schede/abruzzo/1300310044_AQ_B...
3,abruzzo,1300310088_CH_Casoli_EDSING_scala est,0.original_foto_schede/abruzzo/1300310088_CH_C...
4,abruzzo,1300310328_PE_Penne_EDSING_casa pendio_Formica2,0.original_foto_schede/abruzzo/1300310328_PE_P...
5,abruzzo,1300310329_PE_Penne_EDSING_casolare_Formica3,0.original_foto_schede/abruzzo/1300310329_PE_P...
6,abruzzo,1300310587_TE_Notaresco_EDANN_casa,0.original_foto_schede/abruzzo/1300310587_TE_N...
7,abruzzo,1300310722_CH_Frisa_EDANN_casolare,0.original_foto_schede/abruzzo/1300310722_CH_F...
8,abruzzo,1300310736_AQ_Castel di Sangro_EDSING_Masseria...,0.original_foto_schede/abruzzo/1300310736_AQ_C...
9,abruzzo,1300310738_AQ_Castel di Sangro_EDANN_Masseria ...,0.original_foto_schede/abruzzo/1300310738_AQ_C...
10,abruzzo,1300310867_TE_EDANN_casa con torre_Mezzanotte,0.original_foto_schede/abruzzo/1300310867_TE_E...
11,abruzzo,1300311099_Martinsicuro_EDANN_scala esterna_ca...,0.original_foto_schede/abruzzo/1300311099_Mart...
12,abruzzo,1300311422_TE_Campli_COM_casa a edifici affian...,0.original_foto_schede/abruzzo/1300311422_TE_C...
13,abruzzo,1300311545_CH_Celenza sul Trigno_EDANN_scalaes...,0.original_foto_schede/abruzzo/1300311545_CH_C...
14,abruzzo,1300311639_CH_Ripa Teatina_casa con torre_Casa...,0.original_foto_schede/abruzzo/1300311639_CH_R...
15,abruzzo,1300311644_TE_Atri_COM_Masseria NO è una scala...,0.original_foto_schede/abruzzo/1300311644_TE_A...
16,abruzzo,1300311790_Montazzoli_EDANN_casolare_Masseria ...,0.original_foto_schede/abruzzo/1300311790_Mont...
17,abruzzo,1300311799_Vicoli_EDSING_casa con torre_Contra...,0.original_foto_schede/abruzzo/1300311799_Vico...
18,abruzzo,1300312018_CH_Casa in località Colle Marcone_E...,0.original_foto_schede/abruzzo/1300312018_CH_C...
19,basilicata,1700223823_PZ_Roccanova_edificio singolo_casa ...,0.original_foto_schede/basilicata/1700223823_P...
20,basilicata,1700223900_MT_Matera_complesso_masseria,0.original_foto_schede/basilicata/1700223900_M...
21,basilicata,1700223921_PZ_Senise_edificio singolo_casa a p...,0.original_foto_schede/basilicata/1700223921_P...
22,basilicata,1700223927_MT_Matera_complesso_masseria,0.original_foto_schede/basilicata/1700223927_M...
23,basilicata,1700223942_PZ_Senise_edificio singolo_casa di ...,0.original_foto_schede/basilicata/1700223942_P...
24,basilicata,1700223963_MT_S.Giorgio Lucano_edificio singol...,0.original_foto_schede/basilicata/1700223963_M...
25,basilicata,1700223985_PZ_S.Arcangelo_edificio con annessi...,0.original_foto_schede/basilicata/1700223985_P...
26,basilicata,1700224712_PZ_Satriano di Lucania_edificio sin...,0.original_foto_schede/basilicata/1700224712_P...
27,basilicata,1700224713_PZ_Satriano_edificio singolo_casa a...,0.original_foto_schede/basilicata/1700224713_P...
28,basilicata,1700224722_PZ_Satriano di Lucania_edificio con...,0.original_foto_schede/basilicata/1700224722_P...
29,basilicata,1700224729_PZ_Satriano di Lucania_complesso_in...,0.original_foto_schede/basilicata/1700224729_P...
30,basilicata,1700224740_PZ_Savoia di Lucania_edificio singo...,0.original_foto_schede/basilicata/1700224740_P...
31,basilicata,1700224768_PZ_Marsico Nuovo_complesso_masseria,0.original_foto_schede/basilicata/1700224768_P...
32,basilicata,1700224770_PZ_Marsico Nuovo_complesso_masseria,0.original_foto_schede/basilicata/1700224770_P...
33,basilicata,1700224774_PZ_Marsico Nuovo_complesso_masseria,0.original_foto_schede/basilicata/1700224774_P...
34,basilicata,1700224796_MT_Miglionico_complesso_masseria,0.original_foto_schede/basilicata/1700224796_M...
35,basilicata,1700225490_PZ_Ginestra_edificio con annessi_ca...,0.original_foto_schede/basilicata/1700225490_P...
36,basilicata,1700225563_PZ_Guardia Perticara_edificio singo...,0.original_foto_schede/basilicata/1700225563_P...
37,calabria,1800178855_KR_Cirò_edificio singolo_masseria f...,0.original_foto_schede/calabria/1800178855_KR_...
38,calabria,1800178863_KR_Cutro_complesso_masseria a corte,0.original_foto_schede/calabria/1800178863_KR_...
39,calabria,1800178881_RC_Gioiosa Jonica_edificio con anne...,0.original_foto_schede/calabria/1800178881_RC_...
40,calabria,1800194432_KR_Cirò Marina_complesso_casa edifi...,0.original_foto_schede/calabria/1800194432_KR_...
41,calabria,1800194451_KR_Crotone_complesso_masseria con t...,0.original_foto_schede/calabria/1800194451_KR_...
42,calabria,1800194557_KR_Cirò Marina_complesso_masseria a...,0.original_foto_schede/calabria/1800194557_KR_...
43,calabria,1800194559_KR_Crucoli_complesso_masseria forti...,0.original_foto_schede/calabria/1800194559_KR_...
44,calabria,1800194904_KR_Petilia Policastro_edificio sing...,0.original_foto_schede/calabria/1800194904_KR_...
45,calabria,1800194944_VV_Nicotera_complesso_masseria,0.original_foto_schede/calabria/1800194944_VV_...
46,calabria,1800194970_VV_Drapia_edificio con annessi_casale,0.original_foto_schede/calabria/1800194970_VV_...
47,calabria,1800196527_RC_Oppido Mamertina_edificio con an...,0.original_foto_schede/calabria/1800196527_RC_...
48,calabria,1800197333_VV_Nicotera_edificio singolo_casale,0.original_foto_schede/calabria/1800197333_VV_...
49,calabria,1800197526_VV_Zungri_edificio con annessi_casale,0.original_foto_schede/calabria/1800197526_VV_...

Detected data-point folders: 489